export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";

export const ADD_TO_FAVOURITE_OFFER = "ADD_TO_FAVOURITE_OFFER";

export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";

export const REMOVE_FROM_FAVOURITE_OFFER = "REMOVE_FROM_FAVOURITE_OFFER";

