export const ALL_OFFERPRODUCT_REQUEST = "ALL_OFFERPRODUCT_REQUEST";
export const ALL_OFFERPRODUCT_SUCCESS = "ALL_OFFERPRODUCT_SUCCESS";
export const ALL_OFFERPRODUCT_FAIL = "ALL_OFFERPRODUCT_FAIL";

export const ADMIN_OFFERPRODUCT_REQUEST = "ADMIN_OFFERPRODUCT_REQUEST";
export const ADMIN_OFFERPRODUCT_SUCCESS = "ADMIN_OFFERPRODUCT_SUCCESS";
export const ADMIN_OFFERPRODUCT_FAIL = "ADMIN_OFFERPRODUCT_FAIL";

export const NEW_OFFERPRODUCT_REQUEST = "NEW_OFFERPRODUCT_REQUEST";
export const NEW_OFFERPRODUCT_SUCCESS = "NEW_OFFERPRODUCT_SUCCESS";
export const NEW_OFFERPRODUCT_RESET = "NEW_OFFERPRODUCT_RESET";
export const NEW_OFFERPRODUCT_FAIL = "NEW_OFFERPRODUCT_FAIL";

export const UPDATE_OFFERPRODUCT_REQUEST = "UPDATE_OFFERPRODUCT_REQUEST";
export const UPDATE_OFFERPRODUCT_SUCCESS = "UPDATE_OFFERPRODUCT_SUCCESS";
export const UPDATE_OFFERPRODUCT_RESET = "UPDATE_OFFERPRODUCT_RESET";
export const UPDATE_OFFERPRODUCT_FAIL = "UPDATE_OFFERPRODUCT_FAIL";

export const DELETE_OFFERPRODUCT_REQUEST = "DELETE_OFFERPRODUCT_REQUEST";
export const DELETE_OFFERPRODUCT_SUCCESS = "DELETE_OFFERPRODUCT_SUCCESS";
export const DELETE_OFFERPRODUCT_RESET = "DELETE_OFFERPRODUCT_RESET";
export const DELETE_OFFERPRODUCT_FAIL = "DELETE_OFFERPRODUCT_FAIL";

export const OFFERPRODUCT_DETAILS_REQUEST = "OFFERPRODUCT_DETAILS_REQUEST";
export const OFFERPRODUCT_DETAILS_SUCCESS = "OFFERPRODUCT_DETAILS_SUCCESS";
export const OFFERPRODUCT_DETAILS_FAIL = "OFFERPRODUCT_DETAILS_FAIL";

export const NEW_OFFERREVIEW_REQUEST = "NEW_OFFERREVIEW_REQUEST";
export const NEW_OFFERREVIEW_SUCCESS = "NEW_OFFERREVIEW_SUCCESS";
export const NEW_OFFERREVIEW_RESET = "NEW_OFFERREVIEW_RESET";
export const NEW_OFFERREVIEW_FAIL = "NEW_OFFERREVIEW_FAIL";

export const ALL_OFFERREVIEW_REQUEST = "ALL_OFFERREVIEW_REQUEST";
export const ALL_OFFERREVIEW_SUCCESS = "ALL_OFFERREVIEW_SUCCESS";
export const ALL_OFFERREVIEW_FAIL = "ALL_OFFERREVIEW_FAIL";

export const DELETE_OFFERREVIEW_REQUEST = "DELETE_OFFERREVIEW_REQUEST";
export const DELETE_OFFERREVIEW_SUCCESS = "DELETE_OFFERREVIEW_SUCCESS";
export const DELETE_OFFERREVIEW_RESET = "DELETE_OFFERREVIEW_RESET";
export const DELETE_OFFERREVIEW_FAIL = "DELETE_OFFERREVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";